name: Update Docker Compose

on:
  repository_dispatch:
    types: [docker_image_published]

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update compose.yml in correct path
        run: |
          CONTAINER_NAME="${{ github.event.client_payload.container_name }}"
          IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
          APP_NAME="${{ github.event.client_payload.app_name }}"
          COMPOSE_PATH="$APP_NAME/compose.yml"

          echo "Updating $CONTAINER_NAME to tag $IMAGE_TAG in $COMPOSE_PATH"

          if [ -f "$COMPOSE_PATH" ]; then
            sed -i "s|\($CONTAINER_NAME:\).*|\1$IMAGE_TAG|" "$COMPOSE_PATH"
          else
            echo "ERROR: $COMPOSE_PATH does not exist"
            exit 1
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update ${{ github.event.client_payload.container_name }} image to tag ${{ github.event.client_payload.image_tag }} in ${{ github.event.client_payload.app_name }}"
          git push https://${{ secrets.REPO_TOKEN }}@github.com/${{ github.repository }} HEAD:main
